rename log and log_err to info and err. do not show "success" anymore (exit 0 = success). introduce new error for invalid token

diff --git a/pushbullet b/pushbullet
--- a/pushbullet
+++ b/pushbullet
@@ -7,18 +7,18 @@ API_URL=https://api.pushbullet.com/v2
 PROGDIR="$(cd "$( dirname "$0" )" && pwd )"
 unset QUIET
 
-log() {
+info() {
 	if [[ -z ${QUIET} ]]; then
 		echo $@
 	fi
 }
 
-log_err() {
+err() {
 	echo $@ > /dev/stderr
 }
 
 if [ ! $(which curl) ]; then
-	log_err "pushbullet-bash requires curl to run. Please install curl"
+	err "pushbullet-bash requires curl to run. Please install curl"
 	exit 1
 fi
 
@@ -30,7 +30,7 @@ source $PB_CONFIG > /dev/null 2>&1
 
 # don't give warning when script is called with setup option
 if [[ -z "$PB_API_KEY" ]] && [[ "$1" != "setup" ]]; then
-	log_err -e "\e[0;33mWarning, your API key is not set.\nPlease create \"$PB_CONFIG\" with a line starting with PB_API_KEY= and your PushBullet key\e[00m"
+	err -e "\e[0;33mWarning, your API key is not set.\nPlease create \"$PB_CONFIG\" with a line starting with PB_API_KEY= and your PushBullet key\e[00m"
 	exit 1
 fi
 
@@ -90,13 +90,15 @@ function getactivepushes () {
 checkCurlOutput() {
 	res=$(echo "$1" | grep -o "created" | tail -n1)
 	if [[ "$1" == *"The param 'channel_tag' has an invalid value."* ]] && [[ "$1" == *"The param 'device_iden' has an invalid value."* ]]; then
-		log_err "Error: You specified an unknown device or channel."
+		err "Error: You specified an unknown device or channel."
+		exit 1
+	elif [[ "$1" == *"invalid_access_token"* ]]; then
+		err "Access token is missing or invalid."
 		exit 1
 	elif [[ "$res" != "created" ]] && [[ ! "$1" == "{}" ]]; then
-		log_err "Error submitting the request. The error message was:" $1
+		err "Error submitting the request. The error message was:" $1
 		exit 1
 	fi
-	log "Success"
 }
 
 case $1 in
@@ -159,7 +161,7 @@ delete)
 		printUsage
 		;;
 	all)
-		log "deleting all pushes"
+		info "deleting all pushes"
 		curlres=$(curl -s "$API_URL/pushes" -H "Access-Token: $PB_API_KEY" -H "Content-Type: application/json" -X DELETE)
 		checkCurlOutput "$curlres"
 		;;
@@ -168,7 +170,7 @@ delete)
 		if [ -z "${3##*[!0-9]}" ]; then
 			printUsage
 		fi
-		log "deleting all pushes except the last $3"
+		info "deleting all pushes except the last $3"
 		number=$(($3+1))
 		allpushes=$(curl -s "$API_URL/pushes?active=true" -H "Access-Token: $PB_API_KEY" -H "Content-Type: application/json" | "$PROGDIR"/JSON.sh -l)
 		activepushes=$(echo "$allpushes" | egrep "\[\"pushes\",[0-9]+,\"active\"\].*true"|while read line; do echo "$line"|cut -f 2 -d ,; done | tail -n "+$number")
@@ -178,7 +180,7 @@ delete)
 		done
 		;;
 	*)
-		log "deleting $2"
+		info "deleting $2"
 		curlres=$(curl -s "$API_URL/pushes/$2" -H "Access-Token: $PB_API_KEY" -H "Content-Type: application/json" -X DELETE)
 		checkCurlOutput "$curlres"
 		;;
@@ -232,14 +234,14 @@ push)
 	link)
 		type=link
 		if [[ ! $url == http://* ]] && [[ ! $url == https://* ]]; then
-			log_err "Error: A valid link has to start with http:// or https://"
+			err "Error: A valid link has to start with http:// or https://"
 			exit 1
 		fi
 		json="{\"type\":\"$type\",\"title\":\"$title\",\"body\":\"$body\",\"url\":\"$url\""
 	;;
 	file)
 		if [[ -z $4 ]] || [[ ! -f $4 ]]; then
-			log_err "Error: no valid file to push was specified"
+			err "Error: no valid file to push was specified"
 			exit 1
 		fi
 		# Api docs: https://docs.pushbullet.com/v2/upload-request/
@@ -260,19 +262,19 @@ push)
 	esac
 
 	if [ "$2" = "all" ]; then
-		log "Sending to All Devices"
+		info "Sending to All Devices"
 		json="$json}"
 	# $2 must be a contact/an email address if it contains an @.
 	elif [[ "$2" == *@* ]]; then
-		log "Sending to email address $2"
+		info "Sending to email address $2"
 		json="$json,\"email\":\"$2\"}"
 	# $2 must be a channel_tag if $lineNum is empty.
 	elif [ -z "$lineNum" ]; then
-		log "Sending to channel $2"
+		info "Sending to channel $2"
 		json="$json,\"channel_tag\":\"$2\"}"
 	# in all other cases $2 must be the identifier of a device.
 	else
-		log "Sending to device $2"
+		info "Sending to device $2"
 		json="$json,\"device_iden\":\"$dev_id\"}"
 	fi
 	curlres=$(curl -s "$API_URL/pushes" -H "Access-Token: $PB_API_KEY" -H "Content-type: application/json" --data-binary "$json" -X POST)
@@ -282,12 +284,12 @@ setup)
 	CLIENT_ID=RP56dyRen86HaaLnXBevnrDTHT8fTcr6
 	REDIRECT_URI="https://Red5d.github.io/pushbullet-bash"
 	OAUTH_URL="https://www.pushbullet.com/authorize?client_id=$CLIENT_ID&redirect_uri=$REDIRECT_URI&response_type=token&scope=everything"
-	log
-	log "Please open the following URL manually if it did not open automatically:"
-	log
+	info
+	info "Please open the following URL manually if it did not open automatically:"
+	info
 	echo "$OAUTH_URL"
-	log
-	log "Before continuing you need to save your newly created token in $PB_CONFIG"
+	info
+	info "Before continuing you need to save your newly created token in $PB_CONFIG"
 
 	if [ "$(uname)" == "Darwin" ]; then
 		open "$OAUTH_URL"
