still much todo..

diff --git a/pushbullet b/pushbullet
--- a/pushbullet
+++ b/pushbullet
@@ -79,13 +79,15 @@ exit 1
 }
 
 function getactivepushes () {
+	# first command in a function reads stdin
 	allpushes=$("$PROGDIR"/JSON.sh -l)
-	activepushes=$(echo "$allpushes" | egrep "\[\"pushes\",[0-9]+,\"active\"\].*true"|while read line; do echo "$line"|cut -f 2 -d ,; done)
+	# TODO simplify with the powers of json.sh
+	activepushes=$(echo "$allpushes" | egrep "\[[0-9]+,\"pushes\",[0-9]+,\"active\"\].*true"|while read line; do echo "$line"|cut -f 2 -d ,; done)
 	for id in $activepushes; do
-		iden=$(echo "$allpushes" | grep "^\[\"pushes\",$id,\"iden\"\]"|cut -f 2)
-		title=$(echo "$allpushes" | grep "^\[\"pushes\",$id,\"title\"\]"|cut -f 2)
-		modified=$(echo "$allpushes" | grep "^\[\"pushes\",$id,\"modified\"\]"|cut -f 2)
-		type=$(echo "$allpushes" | grep "^\[\"pushes\",$id,\"type\"\]"|cut -f 2)
+		iden=$(echo "$allpushes" | grep "^\[[0-9]+,\"pushes\",$id,\"iden\"\]"|cut -f 2)
+		title=$(echo "$allpushes" | grep "^\[[0-9]+,\"pushes\",$id,\"title\"\]"|cut -f 2)
+		modified=$(echo "$allpushes" | grep "^\[[0-9]+,\"pushes\",$id,\"modified\"\]"|cut -f 2)
+		type=$(echo "$allpushes" | grep "^\[[0-9]+,\"pushes\",$id,\"type\"\]"|cut -f 2)
 		if [[ -z "$title" ]]; then
 			title="(no title)"
 		fi
@@ -101,6 +103,12 @@ checkCurlOutput() {
 	elif [[ "$1" == *"invalid_access_token"* ]]; then
 		err "Access token is missing or invalid."
 		exit 1
+	elif [[ "$1" == *"Object not found"* ]]; then
+		err "Object not found"
+		exit 1
+	elif [[ "$1" == '{"accounts":[],"blocks":[],"channels":[],"chats":[],"clients":[],"contacts":[],"devices":[],"grants":[],"pushes":[],"profiles":[],"subscriptions":[],"texts":[]}' ]]; then
+		# "empty" response
+		exit 0
 	elif [[ "$res" != "created" ]] && [[ ! "$1" == "{}" ]]; then
 		err "Error submitting the request. The error message was:" "$1"
 		exit 1
@@ -109,7 +117,8 @@ checkCurlOutput() {
 
 # function prints the cursor function if another page is needed
 checkPagination() {
-	cursor=$(echo "$1" | tr ',' '\n' | grep \"cursor\": | sort -n | cut -d '"' -f4)
+	cursor=$(echo "$1" | JSON.sh -l | tail -n 1 | cut -d '"' -f4)
+	#cursor=$(echo "$1" | tr ',' '\n' | grep \"cursor\": | cut -d '"' -f4)
 	echo "$cursor"
 }
 
@@ -149,8 +158,9 @@ getDevices() {
 }
 
 getPushes() {
+	# function gets a list of pushes
 	local OPTIND
-	while getopts "aim:" OPTION; do
+	while getopts ":a:i:m:" OPTION; do
 		case "$OPTION" in
 		a)
 			active="$OPTARG"
@@ -164,15 +174,19 @@ getPushes() {
 		esac
 	done
 	shift $((OPTIND-1))
+
 	# default to true to only get active pushes if not set otherwise
 	active=${active:-true}
+
+	# default to not giving the json response
+	json=${json:-false}
 
 	# default to 0 to get all pushes if not set otherwise
 	modified=${modified:-0}
 
-	# if $iden is set, add leading slash
-	if [ ! -z $iden ]; then
-		iden=/$iden
+	# if $iden is not set, add leading slash
+	if [ ! -z "$iden" ]; then
+		iden="/$iden"
 	fi
 
 	curlres=$(curl --silent --header "Access-Token: $PB_API_KEY" \
@@ -181,9 +195,9 @@ getPushes() {
 	--get \
 	"$API_URL/pushes$iden")
 	checkCurlOutput "$curlres"
-	echo $curlres | getactivepushes
+	response="[ $curlres"
 
-	# check if query needs pagination, also stoprequesting more pages if the cursor repeats
+	# check if query needs pagination, also stop requesting more pages if the cursor repeats
 	until [ -z "$(checkPagination "$curlres")" ] || [ "$(checkPagination "$curlres")" == "$prevcursor" ]; do
 		curlres=$(curl --silent --header "Access-Token: $PB_API_KEY" \
 		--data-urlencode active="$active" \
@@ -191,9 +205,11 @@ getPushes() {
 		--data-urlencode cursor="$(checkPagination "$curlres")" \
 		--get \
 		"$API_URL/pushes$iden")
-		echo $curlres | getactivepushes
+		response="$response, $curlres"
 		prevcursor="$(checkPagination "$curlres")"
+		#checkCurlOutput "$curlres"
 	done
+	echo "$response ]"
 }
 
 case $1 in
@@ -257,10 +273,13 @@ chat)
 	;;
 pushes)
 	case $2 in
+	debug)
+		getPushes 
+		;;
 	active)
 		info "Your active pushes:"
 		info "------------------"
-		getPushes
+		getPushes | getactivepushes
 		;;
 	recent)
 		# set LASTMODIFIED (unix time) to zero if empty
@@ -270,14 +289,14 @@ pushes)
 		fi
 		info "Your recent pushes:"
 		info "------------------"
-		getPushes -m $PB_LASTMODIFIED
+		getPushes -m $PB_LASTMODIFIED | getactivepushes
 		# TODO how to get $modified for the latest (first) entry?
 		sed --follow-symlinks -i "s/^PB_LASTMODIFIED=.*/PB_LASTMODIFIED=$(date +%s)/" $PB_CONFIG
 		;;
 	last24h)
 		info "Your pushes from the last 24 hours:"
 		info "------------------"
-		getPushes -m $(date -d "1 day ago" +%s)
+		getPushes -m $(date -d "1 day ago" +%s) | getactivepushes
 		;;
 	*)
 		printUsage
@@ -303,10 +322,7 @@ delete)
 		fi
 		info "deleting all pushes except the last $3"
 		number=$(($3+1))
-		allpushes=$(curl --silent --header "Access-Token: $PB_API_KEY" \
-		--data-urlencode active="true" \
-		--get \
-		"$API_URL/pushes" | "$PROGDIR"/JSON.sh -l)
+		allpushes=$(getPushes -j true | "$PROGDIR"/JSON.sh -l)
 		activepushes=$(echo "$allpushes" | egrep "\[\"pushes\",[0-9]+,\"active\"\].*true"|while read line; do echo "$line"|cut -f 2 -d ,; done | tail -n "+$number")
 		for id in $activepushes; do
 			iden=$(echo "$allpushes" | grep "^\[\"pushes\",$id,\"iden\"\]"|cut -f 2 | cut -d'"' -f 2)
@@ -329,9 +345,7 @@ pull)
 		printUsage
 		;;
 	*)
-		curl --silent --header "Access-Token: $PB_API_KEY" \
-		--header "Content-Type: application/json" \
-		"$API_URL/pushes/$2" | "$PROGDIR"/JSON.sh -b
+		getPushes -i $2 -j true | "$PROGDIR"/JSON.sh -b
 		;;
 	esac
 	;;
